### ISSUE TITLE
Not clear host the cipher key was determined - not covered in the presentation

### ISSUE THREAD

**Issue by abelouso** [ereuter/PyEOT#3]
Hello,
 This is not an issue, but rather a question. How did you determine the cipher_key bits? I have converted your program to decode HOT and I am receiving what appear to be good packets. I figured out the forward BCH correction (import galois), but I can't match the expected ECC portion with the actually received one. The BCH complains that there are too many bit errors. The BCH(63,30) used in HOT packet can tolerate up to 6 bit errors, but it gives up because the ECC portion is way off. I was not able to guess the XOR cipher by XOR'ing the received vs expected ECC (the expected is calculated based on received databits), but the resulting bit combination is always different for different unit address (it is, however, the same for all packets from the same unit address - strange)

Thank you very much in advance. You have created very cool tool!

**Comment by ereuter** [comment]
There is no cipher for HOT for whatever reason.  I wrote a version of this to decode the HOT but never published it.  I'll add a folder with those files.  I don't know how much testing I did on it.

**Comment by abelouso** [comment]
Thank you for uploading HOT. It worked for me. I added the BCH error correction to both EOT and HOT, now receiving many more packets.  Here is the code sample for EOT:
<pre>
import galois
...
gBCH = galois.BCH(63,45)
...
def bitStrToGF(bch, bitStr, rev=True):
    if rev:
        bitStr = bitStr[::-1]
    arr = bch.field.Random(len(bitStr))
    for idx in range(0,len(bitStr)):
        if idx < len(bitStr):
            arr[idx] = int(bitStr[idx])
        else:
            break
    return arr

def GFtoStr(gf,rev=False):
    retStr = ""
    for bit in gf:
        retStr += str(bit)
    return retStr

class EOT_decode():
    def __init__(self, buffer, powerMap):
        if (isinstance(buffer, str)):
            self.corrected = ""
            self.packet = buffer[0:74]
            self.generator = '1111001101000001111'  # BCH generator polynomial
            self.cipher_key = '101011011101110000'  # XOR cipher key
            self.data_block = self.packet[11:56]
            self.data_blockR = reverse(self.data_block)
            self.checkbits = checkbits(self.data_blockR, self.generator)
            self.checkbits_cipher = xor(self.checkbits, self.cipher_key)
            self.checkbitsRx = self.packet[56:74]
            self.valid = (self.checkbits_cipher == self.checkbitsRx)  # a match?
            if not self.valid:
                #attempt to correc it
                rxCodeWrdStr = self.data_block + self.checkbitsRx[::-1]
                rxCodeWordGF = bitStrToGF(gBCH,rxCodeWrdStr,False)
                expCodeGF, N = gBCH.decode(rxCodeWordGF,errors=True,output="codeword")
                expCodeStr = GFtoStr(expCodeGF,rev=False)
                if N >= 0:
                    self.packet = self.packet[:11] + expCodeStr[0:gBCH.k] + expCodeStr[gBCH.k:][::-1]
                    self.valid = True
                    self.corrected = "*"
</pre>
I think this question could be closed.
